In [1]:
import tensorflow as tf

In [2]:
a = tf.constant([[1,2,3]])

In [3]:
a.shape

TensorShape([1, 3])

In [4]:
a.ndim

2

In [5]:
a = a*2

In [6]:
a

<tf.Tensor: shape=(1, 3), dtype=int32, numpy=array([[2, 4, 6]])>

In [7]:
a = a+a
a

<tf.Tensor: shape=(1, 3), dtype=int32, numpy=array([[ 4,  8, 12]])>

In [8]:
a = tf.concat([a,a,a], axis = 1)
a = tf.concat([a,a,a], axis = 0)

In [9]:
a

<tf.Tensor: shape=(3, 9), dtype=int32, numpy=
array([[ 4,  8, 12,  4,  8, 12,  4,  8, 12],
       [ 4,  8, 12,  4,  8, 12,  4,  8, 12],
       [ 4,  8, 12,  4,  8, 12,  4,  8, 12]])>

# a+ for Matrix addition
# a- for Matrix Subtraction
# a@ for Matrix Multiplication

In [10]:
tf.reduce_sum(a) #Gives sum of all elements

<tf.Tensor: shape=(), dtype=int32, numpy=216>

In [12]:
if tf.config.list_physical_devices('GPU'):
    print('tensorFlow is using GPU')
else:
    print('tensorFlow is not using GPU')

tensorFlow is not using GPU


In [17]:
rank1_tensor = tf.constant([1,2,3])
rank2_tensor = tf.constant([[1,2], [3,4]])
rank3_tensor = tf.constant([[[1,2], [2,3]], [[3,4], [4,5]]])
rank4_tensor = tf.constant([[[[1,2], [2,3]], [[3,4], [4,5]]],[[[1,2], [2,3]], [[3,4], [4,5]]]])

In [18]:
rank4_tensor.shape

TensorShape([2, 2, 2, 2])

In [28]:
rank4_concat_row = tf.concat([rank4_tensor, rank4_tensor, rank4_tensor, rank4_tensor],axis = 1)

In [29]:
rank4_concat_row

<tf.Tensor: shape=(2, 8, 2, 2), dtype=int32, numpy=
array([[[[1, 2],
         [2, 3]],

        [[3, 4],
         [4, 5]],

        [[1, 2],
         [2, 3]],

        [[3, 4],
         [4, 5]],

        [[1, 2],
         [2, 3]],

        [[3, 4],
         [4, 5]],

        [[1, 2],
         [2, 3]],

        [[3, 4],
         [4, 5]]],


       [[[1, 2],
         [2, 3]],

        [[3, 4],
         [4, 5]],

        [[1, 2],
         [2, 3]],

        [[3, 4],
         [4, 5]],

        [[1, 2],
         [2, 3]],

        [[3, 4],
         [4, 5]],

        [[1, 2],
         [2, 3]],

        [[3, 4],
         [4, 5]]]])>

In [30]:
rank4_concat_col = tf.concat([rank4_tensor, rank4_tensor, rank4_tensor, rank4_tensor],axis = 0)
rank4_concat_col

<tf.Tensor: shape=(8, 2, 2, 2), dtype=int32, numpy=
array([[[[1, 2],
         [2, 3]],

        [[3, 4],
         [4, 5]]],


       [[[1, 2],
         [2, 3]],

        [[3, 4],
         [4, 5]]],


       [[[1, 2],
         [2, 3]],

        [[3, 4],
         [4, 5]]],


       [[[1, 2],
         [2, 3]],

        [[3, 4],
         [4, 5]]],


       [[[1, 2],
         [2, 3]],

        [[3, 4],
         [4, 5]]],


       [[[1, 2],
         [2, 3]],

        [[3, 4],
         [4, 5]]],


       [[[1, 2],
         [2, 3]],

        [[3, 4],
         [4, 5]]],


       [[[1, 2],
         [2, 3]],

        [[3, 4],
         [4, 5]]]])>

In [33]:
rank4_zeroes_tensor = tf.zeros([1,2,3,4,5])

rank4_zeroes_tensor

<tf.Tensor: shape=(1, 2, 3, 4, 5), dtype=float32, numpy=
array([[[[[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]]],


        [[[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]]]]], dtype=float32)>

In [35]:
print(rank4_zeroes_tensor.dtype,
rank4_zeroes_tensor.ndim,
rank4_zeroes_tensor.shape,
      tf.size(rank4_zeroes_tensor))

<dtype: 'float32'> 5 (1, 2, 3, 4, 5) tf.Tensor(120, shape=(), dtype=int32)


In [36]:
rank2_tensor[:2]

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>

In [42]:
ex = tf.constant([[1,2,3],[4,5,6]])
ex

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [38]:
ex[0][1:]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 3])>

In [39]:
ex[1][1:]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([5, 6])>

In [40]:
ex[0]

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3])>

In [41]:
ex[0][1]

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [43]:
print(ex.shape.as_list())

[2, 3]


In [48]:
ex = tf.cast(ex,dtype = float)

In [49]:
ex = ex*0.8
ex

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0.8, 1.6, 2.4],
       [3.2, 4. , 4.8]], dtype=float32)>

In [52]:
ex = tf.cast(ex,dtype = tf.uint8)

In [53]:
ex

<tf.Tensor: shape=(2, 3), dtype=uint8, numpy=
array([[0, 1, 2],
       [3, 4, 4]], dtype=uint8)>