In [1]:
import tensorflow as tf
print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.9.1


In [2]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

11490434/11490434 [==============================] - 39s 3us/step


In [3]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [4]:
predictions = model(x_train[:1]).numpy()
predictions

array([[-0.87209755,  0.40181202, -0.1472648 ,  0.3549817 ,  0.66777277,
         0.17199758,  0.14143825, -0.35461116,  0.0098027 ,  0.3785115 ]],
      dtype=float32)

In [5]:
tf.nn.softmax(predictions).numpy()

array([[0.035847  , 0.12814589, 0.07400204, 0.12228313, 0.16718988,
        0.10183512, 0.09877017, 0.06014427, 0.08658791, 0.12519455]],
      dtype=float32)

In [6]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [7]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [8]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 4s 1ms/step - loss: 0.2951 - accuracy: 0.9140
Epoch 2/5
1875/1875 [==============================] - 3s 1ms/step - loss: 0.1422 - accuracy: 0.9581
Epoch 3/5
1875/1875 [==============================] - 3s 1ms/step - loss: 0.1075 - accuracy: 0.9667
Epoch 4/5
1875/1875 [==============================] - 3s 1ms/step - loss: 0.0868 - accuracy: 0.9731
Epoch 5/5
1875/1875 [==============================] - 3s 1ms/step - loss: 0.0727 - accuracy: 0.9769


In [9]:
model.evaluate(x_test, y_test, verbose=2)

313/313 - 0s - loss: 0.0803 - accuracy: 0.9749 - 453ms/epoch - 1ms/step


[0.08026327192783356, 0.9749000072479248]

In [10]:
probability_model = tf.keras.Sequential([
    model,
    tf.keras.layers.Softmax()
])

In [11]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[3.56367622e-07, 3.28933183e-08, 9.69142349e-08, 1.07989057e-04,
        5.82112006e-12, 1.93021705e-07, 2.61839866e-13, 9.99879241e-01,
        2.10683410e-07, 1.18391617e-05],
       [1.54500810e-07, 1.93240150e-04, 9.99463022e-01, 2.18485424e-04,
        5.66740004e-15, 4.00104409e-06, 1.21063394e-07, 3.12332490e-14,
        1.21078345e-04, 3.90698021e-12],
       [3.75259006e-08, 9.98505473e-01, 5.13017643e-04, 1.52794037e-05,
        1.86742127e-05, 2.24926748e-06, 2.99384396e-06, 7.50592561e-04,
        1.90253486e-04, 1.48176343e-06],
       [9.99804080e-01, 8.62720299e-07, 4.90361572e-06, 3.06528750e-06,
        1.27605006e-07, 4.66594247e-05, 1.11515392e-05, 7.87722092e-05,
        5.99501732e-07, 4.98251611e-05],
       [7.60471230e-05, 1.11109832e-09, 1.67862891e-05, 2.71887444e-07,
        9.95303035e-01, 1.58762614e-05, 1.86593224e-05, 6.82756217e-05,
        5.42946827e-06, 4.49550338e-03]], dtype=float32)>